force-app/main/default/objects/Einstein_GPT_Config__c/Einstein_GPT_Config__c.object-meta.xml
<CustomObject>
    <label>Einstein GPT Config</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Einstein GPT Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Einstein_GPT_Config__c/fields/Standard_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Standard_Prompt__c</fullName>
    <description>This will always be sent to any prompt you send to OpenAI, whether you&apos;re using one of the built-in components, use the Flow actions or use the chat assistant.</description>
    <inlineHelpText>This will always be sent to any prompt you send to OpenAI, whether you&apos;re using one of the built-in components, use the Flow actions or use the chat assistant.</inlineHelpText>
    <label>Standard Prompt</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/EinsteinGPTConfigManagement.cls
public class EinsteinGPTConfigManagement {

    @AuraEnabled
    public static string getEinsteinGPTStandardPrompt() {
        Einstein_GPT_Config__c egptConfigRecord = [SELECT Id, Standard_Prompt__c FROM Einstein_GPT_Config__c LIMIT 1];

        if (egptConfigRecord != null) {
            return egptConfigRecord.Standard_Prompt__c;
        } else {
            return 'N/A';
        }

    }

    @AuraEnabled
    public static void setEinsteinGPTStandardPrompt(String prompt) {
        List<Einstein_GPT_Config__c> egptConfigRecords = [SELECT Id FROM Einstein_GPT_Config__c LIMIT 1];

        if (egptConfigRecords.size() > 0) {

            // Modify the existing record
            Einstein_GPT_Config__c egptConfigRecord = egptConfigRecords[0];
            egptConfigRecord.Standard_Prompt__c = prompt;
            update egptConfigRecord;

        } else {
            // Create a new record
            Einstein_GPT_Config__c newConfigRecord = new Einstein_GPT_Config__c();
            newConfigRecord.Name = 'EinsteinGPTConfig';
            newConfigRecord.Standard_Prompt__c = prompt;
            insert newConfigRecord;
        }
    }

}